version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    image: mariadb_im
    restart: always
    ports:
      - 3306:3306
    networks:
      - net
    volumes:
      - mariadb-data:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    image: nginx_im
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - wpgx:/var/www/html
    networks:
      - net
  wordpress:
    build:  ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    image: wordpress_im
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: always
    volumes:
      - wpgx:/var/www/html
    networks:
      - net
networks:
  net:
    
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/kali/data/db
      o: bind
  wpgx:
    driver: local
    driver_opts:
      type: volume
      device: /home/kali/data/wp
      o: bind