version: "3"

services:
  mariadb:
    container_name: mariadb
    networks:
    - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    expose:
    - "3306"
    volumes:
      - DB:/var/lib/mysql

  nginx:
    container_name: nginx
    networks:
    - inception
    depends_on:
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    ports:
    - "443:443"
    volumes:
      - WordPress:/var/www/html

  wordpress:
    container_name: wordpress
    networks:
    - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose:
    - "9000"
    volumes:
      - WordPress:/var/www/html

networks:
  inception:

volumes:
  WordPress:
   driver: local
   driver_opts:
     type: "volume"
     o: "bind"
     device: "/home/kali/data"
  DB:
   driver: local
   driver_opts:
     type: "volume"
     o: "bind"
     device: "/home/kali/data"
